### ISSUE TITLE
An unhandled exception of type 'System.AccessViolationException' occurred in Google.OrTools.dll

### ISSUE THREAD

**Issue by zzti** [zdz72113/Algorithm_Examples#1]
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

![image](https://github.com/zdz72113/Algorithm_Examples/assets/5188183/2d509930-f532-469b-97bf-329d6a2bf381)

**Comment by zdz72113** [comment]
updated USAlgo.ClassBalance to 1.0.4
